### ISSUE TITLE
Popup is uncloseable

### ISSUE THREAD

**Issue by pimterry** [piranha/infowarship#1]
I've been testing with a VPN in Russia. When trying to close the popup, it throws an error:

> VM41:1 Uncaught DOMException: Blocked a frame with origin "https://infowarship.pages.dev" from accessing a cross-origin frame.

This happens because the iframe tries to call `window.parent.document.getElementById('infowarship').remove()` but it's running on a page that isn't on the same domain, so it isn't allowed to access `window.parent.document`.

This will affect usage of this script on every site that isn't `https://infowarship.pages.dev`.

To fix this, you need the iframe to indirectly communicate with the original script, and to then remove the iframe from that script instead. That works because the injection script is running on the hosting domain, not in the iframe. More info: https://stackoverflow.com/questions/2182027/close-iframe-cross-domain

**Comment by sansolovyov** [comment]
Oh right! Thanks for the idea, I'll do that a little bit later today.
