### ISSUE TITLE
Low popup visibility

### ISSUE THREAD

**Issue by kstrukov** [piranha/infowarship#3]
Hey folks, 

Any website with this popup will be banned by RKN in a short time - days, for resources with decent traffic maybe even hours - so it would be better to use this time with maximum efficiency. 

This popup now is way too delicate. I would say it should be a full-screen one with a more contrasting background (smth like red& white text on black etc would work).

This is not a rhetoric question - right now I'm adding it to a couple of resources with dozens of thousands of visitors from Russia, and I'd like this information delivered to as many of them as possible before RKN would act).

P.S. Frontend is not my cup of tea, so an issue instead of a PR...

**Comment by nyanja** [comment]
done
